apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom # Match the label of your Prometheus instance as per helm release
spec:
  selector:
    matchLabels:
      app: model # Match the label of your service
  namespaceSelector:
    matchNames:
      - default # or your namespace
  endpoints:
    - port: model # or match name of your service port
      path: /metrics
      interval: 15s