# servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
    - port: "8000"      # <= au lieu de "http"
      path: /metrics
      interval: 15s
      scheme: http