apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: mouhamadou98/fastapi:latest
        name: fastapi
        ports:
        - containerPort: 8000
        resources: {}
status: {}
