apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: mouhamadou98/house-price-backend:latest
        name: house-price-backend
        ports:
        - containerPort: 8000 # Port for the FastAPI application
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
              cpu: "100m"
              memory: "128Mi"
status: {}
