name : MLOps CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:             
  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push FastAPI image
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: mouhamadou98/fastapi:dev

    - name: Build and push Streamlit image
      uses: docker/build-push-action@v4
      with:
        context: ./streamlit_app
        file: ./streamlit_app/Dockerfile
        push: true
        tags: mouhamadou98/streamlit:dev
    - name: Verify FastAPI image